resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    ---
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
          ansible_connection: ssh
          ansible_user: centos
          ansible_become_user: root
    vector:
      hosts:
        vector-01:
          ansible_host: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
          ansible_connection: ssh
          ansible_user: centos
          ansible_become_user: root
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: ${yandex_compute_instance.node03.network_interface.0.nat_ip_address}
          ansible_connection: ssh
          ansible_user: centos
          ansible_become_user: root
    DOC
  filename = "../playbook/inventory/prod.yml"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03
  ]
}
